.include "include/beatscript.inc"
.include "games/spaceball/macros.inc"
.include "games/molecano/macros.inc"


.section .script.entry
@ Spaceball - Script Entry Point

script script_spaceball_entry
    set_tempo 124
    rest 24
    call script_spaceball_prologue
    set_game_fade_in_time 16
    load_spaceball
    enable_play_inputs
    start_tracking_inputs
    call script_spaceball_main
    disable_pause_menu
    disable_play_inputs
    fade_music_out 48
    fade_screen_out 12, BLACK
    rest 24
    rest 24
stop

define_gameplay_scene scene_spaceball, script_spaceball_entry



.section .script.prologue
@ Spaceball - Prologue

script script_spaceball_prologue
    set_game_fade_in_time 8
    load_game spaceball_prologue_engine, 0
    run stop_all_soundplayers
    play_sfx s_jingle_baseball_seqData
    rest 24
    rest 24
    run func_080452e0, 1
    rest 2
    run func_080452e0, 2
    rest 2
    run func_080452e0, 3
    rest 2
    run func_080452e0, 4
    rest 6
    rest 6
    rest 24
    rest 24
    rest 12
    run func_08006d80, 0
    rest 24
    set_game_fade_in_time 16
return



.section .script.main
@ Spaceball - Marking Criteria

struct spaceball_marking_criteria_0
    /* Positive Remark */     .word D_0805bf54
    /* Negative Remark */     .word D_0805bf38
    /* Flags */               .hword CHECK_AVERAGE_HITS | OVERRIDE_COMMENTS | CHECK_AVERAGE_MISSES
    /* Pos: Required Hits */  .hword 0x00 @ 0%
    /* Neg: Minimum Hits */   .hword 0xB3 @ 70%
    /* Neg: Maximum Misses */ .hword 0x4C @ 30%
endstruct

struct spaceball_marking_criteria_1
    /* Positive Remark */     .word D_0805bf70
    /* Negative Remark */     .word D_0805bf58
    /* Flags */               .hword CHECK_AVERAGE_HITS
    /* Pos: Required Hits */  .hword 0xCC @ 80%
    /* Neg: Minimum Hits */   .hword 0x80 @ 50%
    /* Neg: Maximum Misses */ .hword 1
endstruct

struct spaceball_marking_criteria_2
    /* Positive Remark */     .word D_0805bfa8
    /* Negative Remark */     .word D_0805bf8c
    /* Flags */               .hword CHECK_AVERAGE_HITS
    /* Pos: Required Hits */  .hword 0xCC @ 80%
    /* Neg: Minimum Hits */   .hword 0x80 @ 50%
    /* Neg: Maximum Misses */ .hword 2
endstruct

struct spaceball_marking_criteria_3
    /* Positive Remark */     .word D_0805bfe0
    /* Negative Remark */     .word D_0805bfc4
    /* Flags */               .hword CHECK_AVERAGE_HITS
    /* Pos: Required Hits */  .hword 0xCC @ 80%
    /* Neg: Minimum Hits */   .hword 0x80 @ 50%
    /* Neg: Maximum Misses */ .hword 1
endstruct

struct spaceball_marking_criteria
    .word spaceball_marking_criteria_0
    .word spaceball_marking_criteria_1
    .word spaceball_marking_criteria_2
    .word spaceball_marking_criteria_3
    .word END_OF_CRITERIA
endstruct



@ Spaceball - Main Script

script script_spaceball_main
    set_results_header D_0805bff8
    import_marking_criteria spaceball_marking_criteria
    run gameplay_set_mercy_count, 1
    stop_tracking_inputs
    set_tempo 110
    set_music_volume 240
    spaceball_zoom_camera 0xff00, 96
    set_music_volume 60
    mod_music_volume 180, 192
    play_music s_shibafu1_bgm_seqData
    rest 24
    enable_pause_menu
    rest 24
    load_molecano
    rest 24
    rest 24
    play_sfx s_dontan_count_seqData
    rest 24
    play_sfx s_dontan_count_seqData
    spawn_cue 0x00
    rest 48
    spawn_cue 0x00
    rest 48
    spawn_cue 0x00
    rest 48
    spawn_cue 0x00
    rest 48
    spawn_cue 0x00
    rest 24
    spawn_cue 0x02
    rest 48
    rest 48
    play_sfx s_dontan_count_seqData
    rest 12
    play_sfx s_dontan_count_seqData
    rest 12
    play_sfx s_dontan_count_seqData
    rest 12
    play_sfx s_dontan_count_seqData
    spawn_cue 0x01
    rest 24
    spawn_cue 0x01
    rest 24
    spawn_cue 0x01
    rest 24
    play_sfx s_dontan_count_seqData
    spawn_cue 0x01
    
    rest 24
    
    rest 24
    rest 24
    rest 24
    rest 48
    rest 24
    rest 21
    rest 27
    stop_tracking_perfect_campaign
    disable_pause_menu
    rest 24
return

.end
