.include "include/beatscript.inc"
.include "games/night_walk/macros.inc"
.include "games/molecano/macros.inc"

.section .script.entry
@ Night Walk - Script Entry Point

script script_night_walk_entry
    set_tempo 124
    rest 24
    call script_night_walk_prologue
    set_game_fade_in_time 16
    load_molecano
    enable_play_inputs
    start_tracking_inputs
    call script_night_walk_main
    disable_pause_menu
    disable_play_inputs
    fade_music_out 48
    fade_screen_out 12, BLACK
    rest 24
    rest 24
stop

define_gameplay_scene scene_night_walk, script_night_walk_entry



.section .script.prologue
@ Night Walk - Prologue

script script_night_walk_prologue
    set_game_fade_in_time 8
    load_game night_walk_prologue_engine, 0
    run stop_all_soundplayers
    run func_080458ec, 0
    rest 24
    rest 24
    rest 24
    run func_080458ec, 1
    rest 24
    play_sfx s_jingle_handclap_seqData
    rest 24
    rest 24
    rest 24
    rest 24
    rest 24
    run func_08006d80, 0
    rest 24
    set_game_fade_in_time 16
return



.section .script.main
@ Night Walk - Marking Criteria

struct night_walk_marking_criteria_0
    /* Positive Remark */     .word D_0805b174
    /* Negative Remark */     .word D_0805b158
    /* Flags */               .hword OVERRIDE_COMMENTS | CHECK_AVERAGE_MISSES
    /* Pos: Required Hits */  .hword 0x100 @ 100%
    /* Neg: Minimum Hits */   .hword 0x00 @ 0%
    /* Neg: Maximum Misses */ .hword 0x00 @ 0%
endstruct

struct night_walk_marking_criteria_1
    /* Positive Remark */     .word D_0805b1a4
    /* Negative Remark */     .word D_0805b18c
    /* Flags */               .hword CHECK_AVERAGE_HITS | CHECK_AVERAGE_MISSES
    /* Pos: Required Hits */  .hword 0xE6 @ 90%
    /* Neg: Minimum Hits */   .hword 0xCC @ 80%
    /* Neg: Maximum Misses */ .hword 0x100 @ 100%
endstruct

struct night_walk_marking_criteria_2
    /* Positive Remark */     .word D_0805b1dc
    /* Negative Remark */     .word D_0805b1bc
    /* Flags */               .hword CHECK_AVERAGE_HITS | CHECK_AVERAGE_MISSES
    /* Pos: Required Hits */  .hword 0x100 @ 100%
    /* Neg: Minimum Hits */   .hword 0xB3 @ 70%
    /* Neg: Maximum Misses */ .hword 0x100 @ 100%
endstruct

struct night_walk_marking_criteria
    .word night_walk_marking_criteria_0
    .word night_walk_marking_criteria_1
    .word night_walk_marking_criteria_2
    .word END_OF_CRITERIA
endstruct



@ Night Walk - Main Script

script script_night_walk_end
    fade_music_out 96
    rest 24
    rest 24
    rest 24
    rest 24
    rest 24
    rest 24
    rest 24
    disable_pause_menu
    rest 24
    disable_play_inputs
    fade_screen_out 12, BLACK
    rest 24
    rest 24
stop


script script_night_walk_main
    set_results_header D_0805b1f4
    import_marking_criteria night_walk_marking_criteria
    set_marking_criteria 1
    set_tempo 128
    start_tracking_inputs
    run gameplay_assess_irrelevant_inputs, FALSE
    start_perfect_campaign
    rest 24
    enable_pause_menu
    rest 24
    rest 24
    rest 24
    play_music s_4beat_bgm_seqData
    run scene_show_bg_layer, 1
    set_marking_criteria 1
    rest 24
    rest 24
    rest 24
    rest 24
    rest 24
    rest 24
    play_sfx s_dontan_count_seqData
    rest 24
    play_sfx s_dontan_count_seqData
    molecano_left_mole_slow
    rest 24
    spawn_cue CUE_SLOW
    rest 24
    molecano_left_mole_slow
    rest 24
    spawn_cue CUE_SLOW
    rest 24
    molecano_left_mole_slow
    rest 24
    spawn_cue CUE_SLOW
    rest 24
    molecano_left_mole_slow
    rest 24
    spawn_cue CUE_SLOW
    rest 24
    molecano_left_mole_slow
    rest 24
    spawn_cue CUE_SLOW
    rest 24
    molecano_left_mole_slow
    rest 24
    spawn_cue CUE_STOP
    spawn_cue CUE_SLOW
    rest 24
    molecano_left_mole_slow
    rest 48
    @ arp
    rest 24
    play_sfx s_dontan_count_seqData
    rest 24
    play_sfx s_dontan_count_seqData
    molecano_left_mole_slow
    rest 24
    spawn_cue CUE_SLOW
    rest 24
    molecano_left_mole_slow
    rest 24
    spawn_cue CUE_SLOW
    rest 24
    molecano_left_mole_slow
    rest 24
    spawn_cue CUE_SLOW
    rest 24
    molecano_left_mole_slow
    rest 24
    spawn_cue CUE_SLOW
    rest 24
    molecano_left_mole_slow
    rest 24
    spawn_cue CUE_SLOW
    rest 24
    molecano_left_mole_slow
    rest 24
    spawn_cue CUE_SLOW
    rest 24
    molecano_left_mole_slow
    rest 24
    spawn_cue CUE_SLOW
    rest 24
    molecano_left_mole_slow
    rest 24
    play_sfx s_dontan_count_seqData
    spawn_cue CUE_SLOW
    rest 12
    play_sfx s_dontan_count_seqData
    rest 12
    molecano_left_mole_slow
    play_sfx s_dontan_count_seqData
    rest 12
    play_sfx s_dontan_count_seqData
    rest 12
    spawn_cue CUE_FAST
    rest 12
    molecano_left_mole_fast
    rest 12
    spawn_cue CUE_FAST
    rest 12
    molecano_left_mole_fast
    rest 12
    spawn_cue CUE_FAST
    rest 12
    molecano_left_mole_fast
    rest 12
    spawn_cue CUE_FAST
    rest 12
    molecano_left_mole_fast
    rest 12
    spawn_cue CUE_FAST
    rest 12
    molecano_left_mole_fast
    rest 12
    spawn_cue CUE_FAST
    rest 12
    molecano_left_mole_fast
    rest 12
    spawn_cue CUE_FAST
    rest 12
    molecano_left_mole_fast
    rest 12
    spawn_cue CUE_FAST
    rest 12
    molecano_left_mole_fast
    rest 12
    spawn_cue CUE_FAST
    rest 12
    molecano_left_mole_fast
    rest 12
    spawn_cue CUE_FAST
    rest 12
    molecano_left_mole_fast
    rest 12
    spawn_cue CUE_FAST
    rest 12
    molecano_left_mole_fast
    rest 12
    spawn_cue CUE_FAST
    rest 12
    molecano_left_mole_fast
    rest 12
    spawn_cue CUE_FAST
    rest 12
    molecano_left_mole_fast
    rest 12
    spawn_cue CUE_FAST
    rest 12
    molecano_left_mole_fast
    rest 12
    spawn_cue CUE_FAST
    play_sfx s_dontan_count_seqData
    rest 12
    molecano_left_mole_fast
    rest 12
    spawn_cue CUE_FAST
    play_sfx s_dontan_count_seqData
    rest 12
    molecano_left_mole_fast
    rest 12
    @ sloww
    spawn_cue CUE_SLOW
    rest 24
    molecano_left_mole_slow
    rest 24
    spawn_cue CUE_SLOW
    rest 24
    molecano_left_mole_slow
    rest 24
    spawn_cue CUE_SLOW
    rest 24
    molecano_left_mole_slow
    rest 24
    spawn_cue CUE_SLOW
    rest 24
    molecano_left_mole_slow
    rest 24
    spawn_cue CUE_SLOW
    rest 24
    molecano_left_mole_slow
    rest 24
    spawn_cue CUE_STOP
    spawn_cue CUE_SLOW
    rest 24
    molecano_left_mole_slow
    rest 48
    rest 24
    play_sfx s_dontan_count_seqData
    rest 12
    play_sfx s_dontan_count_seqData
    rest 12
    play_sfx s_dontan_count_seqData
    rest 12
    play_sfx s_dontan_count_seqData
    molecano_left_mole_fast
    rest 12
    spawn_cue CUE_FAST
    rest 12
    molecano_left_mole_fast
    rest 12
    spawn_cue CUE_FAST
    rest 12
    molecano_left_mole_fast
    rest 12
    spawn_cue CUE_FAST
    rest 12
    molecano_left_mole_fast
    rest 12
    spawn_cue CUE_FAST
    rest 12
    molecano_left_mole_fast
    rest 12
    spawn_cue CUE_FAST
    rest 12
    molecano_left_mole_fast
    rest 12
    spawn_cue CUE_FAST
    rest 12
    molecano_left_mole_fast
    rest 12
    spawn_cue CUE_FAST
    rest 12
    molecano_left_mole_fast
    rest 12
    spawn_cue CUE_FAST
    rest 12
    molecano_left_mole_fast
    rest 12
    spawn_cue CUE_FAST
    rest 12
    molecano_left_mole_fast
    rest 12
    spawn_cue CUE_FAST
    rest 12
    molecano_left_mole_fast
    rest 12
    spawn_cue CUE_FAST
    rest 12
    molecano_left_mole_fast
    rest 12
    spawn_cue CUE_FAST
    rest 12
    molecano_left_mole_fast
    rest 12
    spawn_cue CUE_FAST
    rest 12
    molecano_left_mole_fast
    rest 12
    spawn_cue CUE_FAST
    rest 12
    molecano_left_mole_fast
    rest 12
    spawn_cue CUE_FAST
    play_sfx s_dontan_count_seqData
    rest 12
    molecano_left_mole_fast
    rest 12
    spawn_cue CUE_FAST
    play_sfx s_dontan_count_seqData
    rest 12
    molecano_left_mole_fast
    rest 12
    @ sloww
    spawn_cue CUE_SLOW
    rest 24
    molecano_left_mole_slow
    rest 24
    spawn_cue CUE_SLOW
    rest 24
    molecano_left_mole_slow
    rest 24
    spawn_cue CUE_SLOW
    rest 24
    molecano_left_mole_slow
    rest 24
    spawn_cue CUE_SLOW
    rest 24
    molecano_left_mole_slow
    rest 24
    spawn_cue CUE_SLOW
    rest 24
    molecano_left_mole_slow
    rest 24
    spawn_cue CUE_SLOW
    rest 24
    molecano_left_mole_slow
    rest 24
    spawn_cue CUE_SLOW
    rest 24
    molecano_left_mole_slow
    rest 24
    spawn_cue CUE_SLOW
    rest 24
    molecano_left_mole_slow
    rest 24
    spawn_cue CUE_SLOW
    rest 24
    molecano_left_mole_slow
    rest 24
    play_sfx s_dontan_count_seqData
    spawn_cue CUE_SLOW
    rest 12
    play_sfx s_dontan_count_seqData
    rest 12
    molecano_left_mole_slow
    play_sfx s_dontan_count_seqData
    rest 12
    play_sfx s_dontan_count_seqData
    rest 12
    spawn_cue CUE_FAST
    rest 12
    molecano_left_mole_fast
    rest 12
    spawn_cue CUE_FAST
    rest 12
    molecano_left_mole_fast
    rest 12
    spawn_cue CUE_FAST
    rest 12
    molecano_left_mole_fast
    rest 12
    spawn_cue CUE_FAST
    rest 12
    molecano_left_mole_fast
    rest 12
    spawn_cue CUE_FAST
    rest 12
    molecano_left_mole_fast
    rest 12
    spawn_cue CUE_FAST
    rest 12
    molecano_left_mole_fast
    rest 12
    spawn_cue CUE_FAST
    rest 12
    molecano_left_mole_fast
    rest 12
    spawn_cue CUE_FAST
    rest 12
    molecano_left_mole_fast
    rest 12
    spawn_cue CUE_FAST
    rest 12
    molecano_left_mole_fast
    rest 12
    spawn_cue CUE_FAST
    rest 12
    molecano_left_mole_fast
    rest 12
    spawn_cue CUE_FAST
    rest 12
    molecano_left_mole_fast
    rest 12
    spawn_cue CUE_FAST
    rest 12
    molecano_left_mole_fast
    rest 12
    spawn_cue CUE_FAST
    rest 12
    molecano_left_mole_fast
    rest 12
    spawn_cue CUE_FAST
    rest 12
    molecano_left_mole_fast
    rest 12
    spawn_cue CUE_FAST
    rest 12
    molecano_left_mole_fast
    rest 12
    spawn_cue CUE_FAST
    rest 12
    molecano_left_mole_fast
    rest 12
    spawn_cue CUE_FAST
    rest 12
    molecano_left_mole_fast
    rest 12
    spawn_cue CUE_FAST
    rest 12
    molecano_left_mole_fast
    rest 12
    spawn_cue CUE_FAST
    rest 12
    molecano_left_mole_fast
    rest 12
    spawn_cue CUE_FAST
    rest 12
    molecano_left_mole_fast
    rest 12
    spawn_cue CUE_FAST
    rest 12
    molecano_left_mole_fast
    rest 12
    spawn_cue CUE_FAST
    rest 12
    molecano_left_mole_fast
    rest 12
    spawn_cue CUE_FAST
    rest 12
    molecano_left_mole_fast
    rest 12
    spawn_cue CUE_FAST
    rest 12
    molecano_left_mole_fast
    rest 12
    spawn_cue CUE_FAST
    rest 12
    molecano_left_mole_fast
    rest 12
    spawn_cue CUE_FAST
    rest 12
    molecano_left_mole_fast
    rest 12
    spawn_cue CUE_FAST
    rest 12
    molecano_left_mole_fast
    rest 12
    spawn_cue CUE_FAST
    rest 12
    molecano_left_mole_fast
    rest 12
    spawn_cue CUE_FAST
    rest 12
    molecano_left_mole_fast
    rest 12
    spawn_cue CUE_FAST
    rest 12
    molecano_left_mole_fast
    rest 12
    spawn_cue CUE_FAST
    play_sfx s_dontan_count_seqData
    rest 12
    molecano_left_mole_fast
    rest 12
    spawn_cue CUE_FAST
    play_sfx s_dontan_count_seqData
    rest 12
    molecano_left_mole_fast
    rest 12
    @ sloww
    spawn_cue CUE_SLOW
    spawn_cue CUE_STOP
    rest 24
    molecano_left_mole_slow
    rest 24


    play_sfx s_dontan_count_seqData
    rest 12
    play_sfx s_dontan_count_seqData
    rest 12
    play_sfx s_dontan_count_seqData
    rest 12
    play_sfx s_dontan_count_seqData
    molecano_left_mole_fast
    rest 12
    spawn_cue CUE_FAST
    rest 12
    molecano_left_mole_fast
    rest 12
    spawn_cue CUE_FAST
    rest 12
    molecano_left_mole_fast
    rest 12
    spawn_cue CUE_FAST
    rest 12
    molecano_left_mole_fast
    rest 12
    spawn_cue CUE_FAST
    rest 12
    molecano_left_mole_fast
    rest 12
    spawn_cue CUE_FAST
    rest 12
    molecano_left_mole_fast
    rest 12
    spawn_cue CUE_FAST
    rest 12
    molecano_left_mole_fast
    rest 12
    spawn_cue CUE_FAST
    rest 12
    molecano_left_mole_fast
    rest 12
    spawn_cue CUE_FAST
    rest 12
    molecano_left_mole_fast
    rest 12
    spawn_cue CUE_FAST
    rest 12
    molecano_left_mole_fast
    rest 12
    spawn_cue CUE_FAST
    rest 12
    molecano_left_mole_fast
    rest 12
    spawn_cue CUE_FAST
    rest 12
    molecano_left_mole_fast
    rest 12
    spawn_cue CUE_FAST
    rest 12
    molecano_left_mole_fast
    rest 12
    spawn_cue CUE_FAST
    rest 12
    molecano_left_mole_fast
    rest 12
    spawn_cue CUE_FAST
    rest 12
    molecano_left_mole_fast
    rest 12
    spawn_cue CUE_FAST
    play_sfx s_dontan_count_seqData
    rest 12
    molecano_left_mole_fast
    rest 12
    spawn_cue CUE_FAST
    play_sfx s_dontan_count_seqData
    rest 12
    molecano_left_mole_fast
    rest 12
    @ sloww
    spawn_cue CUE_SLOW
    rest 24
    molecano_left_mole_slow
    rest 24
    spawn_cue CUE_SLOW
    rest 24
    molecano_left_mole_slow
    rest 24
    spawn_cue CUE_SLOW
    rest 24
    molecano_left_mole_slow
    rest 24
    spawn_cue CUE_SLOW
    rest 24
    molecano_left_mole_slow
    rest 24
    spawn_cue CUE_SLOW
    rest 24
    molecano_left_mole_slow
    rest 24
    spawn_cue CUE_SLOW
    rest 24
    molecano_left_mole_slow
    rest 24
    spawn_cue CUE_SLOW
    rest 24
    molecano_left_mole_slow
    rest 24
    spawn_cue CUE_SLOW
    spawn_cue CUE_STOP
    rest 24
    molecano_left_mole_slow


    rest 24
    rest 24
    rest 48
    rest 24
    rest 24
    rest 24
    disable_pause_menu
    rest 24
return

.end
